import React from "react";
import { Link } from "react-router-dom";
import HeroImage from "../assets/image1.png";
import { BrainCircuit, Video, CheckSquare, CalendarDays, BarChart3, ShieldCheck, GraduationCap, Presentation, Users, ArrowRight } from "lucide-react";

function Home() {
  return (
    <div className="w-full min-h-screen font-sans bg-gray-50">
      
      {/* Navbar */}
      <header className="fixed top-0 z-50 flex justify-between items-center px-6 md:px-16 py-4 bg-white w-full shadow-sm">
        <div className="flex items-center text-xl font-bold text-gray-800">
          <span className="mr-2 text-2xl">🎓</span> EduVexa
        </div>

        <nav className="hidden md:flex space-x-8 text-gray-600 font-medium">
          <a href="#features" className="hover:text-teal-600 transition">Features</a>
          <a href="#roles" className="hover:text-teal-600 transition">For Everyone</a>
          <a href="#about" className="hover:text-teal-600 transition">About</a>
        </nav>

        <div className="flex items-center space-x-4">
          <Link to="/login" className="hidden md:block text-gray-600 hover:text-teal-600 transition font-medium">
            Log in
          </Link>
          <Link to="/register" className="bg-teal-600 text-white px-5 py-2.5 rounded-lg hover:bg-teal-700 transition font-medium inline-block">
            Get Started
          </Link>
        </div>
      </header>

  {/* Hero Section */}
      <section className="relative w-full flex flex-col-reverse md:flex-row items-center justify-between bg-gradient-to-r from-blue-700 to-teal-700 text-white px-6 md:px-20 pt-48 pb-40 md:pt-64 md:pb-64 overflow-hidden">
        
        <div className="md:w-1/2 z-10">
          <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold leading-tight">
            Learn Smarter <br />
            with <span className="text-orange-500">EduVexa</span>
          </h1>

          <p className="mt-6 text-gray-200 text-lg md:text-xl max-w-lg">
            An AI-powered education platform with personalized learning paths,
            smart quizzes, and ML-driven study planners for every learner.
          </p>

          <div className="mt-8 flex flex-wrap gap-4">
            <Link to="/register" className="bg-orange-500 hover:bg-orange-400 text-white px-6 py-3 rounded-lg transition font-medium shadow-lg text-lg flex items-center justify-center">
              Start Learning Free →
            </Link>

            <Link to="/login" className="border border-white text-white px-6 py-3 rounded-lg hover:bg-white hover:text-blue-700 transition font-medium text-lg flex items-center justify-center">
              Sign In
            </Link>
          </div>
        </div>

        <div className="md:w-1/2 flex justify-center relative mb-16 md:mb-0 z-10">
          <div className="absolute w-72 h-72 md:w-96 md:h-96 rounded-full bg-teal-400 opacity-30 blur-3xl animate-pulse"></div>
          <img
            src={HeroImage}
            alt="students"
            className="relative w-80 md:w-[420px] object-contain animate-bounceFloat"
          />
        </div>

        <div className="absolute bottom-0 left-0 w-full h-32 md:h-48 bg-gradient-to-t from-white via-white/80 to-transparent pointer-events-none z-20"></div>
      </section>
      
      {/* Features Section */}
      <section id="features" className="bg-white py-24 px-6 md:px-20 relative z-30">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
            Everything You Need to <span className="text-teal-600">Excel</span>
          </h2>
          <p className="text-gray-500 text-lg">
            Powerful tools designed for modern education, backed by machine learning.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 max-w-7xl mx-auto">
          {[
            { icon: <BrainCircuit className="w-5 h-5 text-teal-600" />, title: "AI-Powered Learning", desc: "Personalized study plans generated by machine learning to match your pace." },
            { icon: <Video className="w-5 h-5 text-teal-600" />, title: "Video Courses", desc: "Watch high-quality lectures uploaded by expert teachers anytime." },
            { icon: <CheckSquare className="w-5 h-5 text-teal-600" />, title: "Smart Quizzes", desc: "Adaptive quizzes that adjust in real-time based on your performance." },
            { icon: <CalendarDays className="w-5 h-5 text-teal-600" />, title: "Timetable Planner", desc: "ML-generated timetables that optimize your study schedule." },
            { icon: <BarChart3 className="w-5 h-5 text-teal-600" />, title: "Progress Analytics", desc: "Track learning progress with detailed charts and insights." },
            { icon: <ShieldCheck className="w-5 h-5 text-teal-600" />, title: "Role-Based Access", desc: "Secure dashboards tailored specifically for students, teachers, and admins." }
          ].map((item, i) => (
            <div key={i} className="bg-white border border-gray-100 p-8 rounded-2xl shadow-[0_2px_15px_-3px_rgba(0,0,0,0.07)] hover:shadow-lg transition-shadow">
              <div className="w-10 h-10 bg-teal-50 rounded-lg flex items-center justify-center mb-6">
                {item.icon}
              </div>
              <h3 className="text-lg font-bold text-gray-900 mb-3">{item.title}</h3>
              <p className="text-gray-500 text-sm leading-relaxed">{item.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Roles Section */}
      <section id="roles" className="bg-gray-50 py-24 px-6 md:px-20">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">Built for Everyone</h2>
          <p className="text-gray-500 text-lg">
            Tailored dashboards for students, teachers, and administrators.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-7xl mx-auto">
          {/* Students */}
          <div className="bg-white p-8 rounded-3xl shadow-sm border border-gray-100 flex flex-col h-full">
            <div className="w-12 h-12 bg-blue-50 text-blue-600 rounded-xl flex items-center justify-center mb-6">
              <GraduationCap className="w-6 h-6" />
            </div>
            <h3 className="text-2xl font-bold text-gray-900 mb-6">Students</h3>
            <ul className="space-y-4 mb-10 flex-grow text-sm">
              <li className="flex items-start text-gray-600"><span className="text-blue-500 mr-3">✓</span> Take quizzes & track scores</li>
              <li className="flex items-start text-gray-600"><span className="text-blue-500 mr-3">✓</span> Watch video courses</li>
              <li className="flex items-start text-gray-600"><span className="text-blue-500 mr-3">✓</span> AI generated study plans</li>
              <li className="flex items-start text-gray-600"><span className="text-blue-500 mr-3">✓</span> Personal progress dashboard</li>
            </ul>
            <Link to="/student" className="flex items-center text-blue-600 font-semibold hover:text-blue-700 transition mt-auto group text-sm">
              Open Students Portal <ArrowRight className="ml-2 w-4 h-4 group-hover:translate-x-1 transition-transform" />
            </Link>
          </div>

          {/* Teachers */}
          <div className="bg-white p-8 rounded-3xl shadow-sm border border-gray-100 flex flex-col h-full">
            <div className="w-12 h-12 bg-teal-50 text-teal-600 rounded-xl flex items-center justify-center mb-6">
              <Presentation className="w-6 h-6" />
            </div>
            <h3 className="text-2xl font-bold text-gray-900 mb-6">Teachers</h3>
            <ul className="space-y-4 mb-10 flex-grow text-sm">
              <li className="flex items-start text-gray-600"><span className="text-teal-500 mr-3">✓</span> Upload courses & videos</li>
              <li className="flex items-start text-gray-600"><span className="text-teal-500 mr-3">✓</span> Create & manage quizzes</li>
              <li className="flex items-start text-gray-600"><span className="text-teal-500 mr-3">✓</span> View student analytics</li>
              <li className="flex items-start text-gray-600"><span className="text-teal-500 mr-3">✓</span> Manage course content</li>
            </ul>
            <Link to="/teacher" className="flex items-center text-teal-600 font-semibold hover:text-teal-700 transition mt-auto group text-sm">
              Open Teachers Portal <ArrowRight className="ml-2 w-4 h-4 group-hover:translate-x-1 transition-transform" />
            </Link>
          </div>

          {/* Admins */}
          <div className="bg-white p-8 rounded-3xl shadow-sm border border-gray-100 flex flex-col h-full">
            <div className="w-12 h-12 bg-orange-50 text-orange-500 rounded-xl flex items-center justify-center mb-6">
              <Users className="w-6 h-6" />
            </div>
            <h3 className="text-2xl font-bold text-gray-900 mb-6">Admins</h3>
            <ul className="space-y-4 mb-10 flex-grow text-sm">
              <li className="flex items-start text-gray-600"><span className="text-orange-500 mr-3">✓</span> Manage user accounts</li>
              <li className="flex items-start text-gray-600"><span className="text-orange-500 mr-3">✓</span> Platform-wide analytics</li>
              <li className="flex items-start text-gray-600"><span className="text-orange-500 mr-3">✓</span> Content moderation</li>
              <li className="flex items-start text-gray-600"><span className="text-orange-500 mr-3">✓</span> System configuration</li>
            </ul>
            <Link to="/admin" className="flex items-center text-orange-500 font-semibold hover:text-orange-600 transition mt-auto group text-sm">
              Open Admins Portal <ArrowRight className="ml-2 w-4 h-4 group-hover:translate-x-1 transition-transform" />
            </Link>
          </div>
        </div>
      </section>

      {/* CTA Banner */}
      <section className="py-20 px-6 md:px-20 bg-white">
        <div className="max-w-6xl mx-auto bg-gradient-to-r from-teal-500 to-blue-700 rounded-[2rem] p-12 md:p-16 text-center text-white shadow-xl">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            Ready to Transform Your Learning?
          </h2>
          <p className="text-teal-50 text-base md:text-lg mb-8 max-w-2xl mx-auto font-light">
            Join EduVexa today and experience personalized, AI-driven education that adapts to you.
          </p>
          <Link to="/register" className="bg-orange-500 hover:bg-orange-400 text-white font-medium py-3 px-8 rounded-lg transition shadow-md inline-flex items-center">
            Get Started Now <span className="ml-2">→</span>
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer id="about" className="bg-gray-50 border-t border-gray-200 pt-16 pb-8 px-6 md:px-20">
        <div className="max-w-7xl mx-auto">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-12 mb-16">
            <div className="col-span-1 md:col-span-1">
              <div className="flex items-center text-xl font-bold mb-4 text-gray-900">
                <span className="text-teal-600 mr-2">🎓</span> EduVexa
              </div>
              <p className="text-gray-500 text-sm leading-relaxed pr-4">
                Empowering education through intelligent technology and personalized learning.
              </p>
            </div>
            <div>
              <h4 className="font-semibold text-gray-900 mb-4 text-sm">Platform</h4>
              <ul className="space-y-3 text-sm text-gray-500">
                <li><a href="#features" className="hover:text-teal-600 transition">Features</a></li>
                <li><a href="#roles" className="hover:text-teal-600 transition">For Students</a></li>
                <li><a href="#roles" className="hover:text-teal-600 transition">For Teachers</a></li>
              </ul>
            </div>
            <div>
              <h4 className="font-semibold text-gray-900 mb-4 text-sm">Resources</h4>
              <ul className="space-y-3 text-sm text-gray-500">
                <li><a href="#" className="hover:text-teal-600 transition">Help Center</a></li>
                <li><a href="#" className="hover:text-teal-600 transition">Documentation</a></li>
                <li><a href="#" className="hover:text-teal-600 transition">Blog</a></li>
              </ul>
            </div>
            <div>
              <h4 className="font-semibold text-gray-900 mb-4 text-sm">Legal</h4>
              <ul className="space-y-3 text-sm text-gray-500">
                <li><a href="#" className="hover:text-teal-600 transition">Privacy Policy</a></li>
                <li><a href="#" className="hover:text-teal-600 transition">Terms of Service</a></li>
              </ul>
            </div>
          </div>
          <div className="border-t border-gray-200 pt-8 flex flex-col md:flex-row justify-between items-center text-sm text-gray-500">
            <p>© 2026 EduVexa. All rights reserved.</p>
            <div className="mt-4 md:mt-0">
              <span className="cursor-pointer hover:text-gray-800 transition">ENG</span>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}

export default Home;